### ISSUE TITLE
Model corresponding to Ours-S-TT

### ISSUE THREAD

**Issue by ksachdeva** [HarshayuGirase/PECNet#1]
Hi,

First thanks for this very well written paper and an innovative approach. 

Your readme mentions that one can reproduce the results from Table 2 of the paper (page 11). In the table, there are 2 models mentioned - Ours-S-TT and PECNet. However, in your repo, you have 3 models. 

Would appreciate if you could suggest which model corresponds to Ours-S-TT

Regards & thanks
Kapil

**Comment by karttikeya** [comment]
Hello,

Thank you — hope the code and paper are helpful. We provide results for final models in the repo, but if helpful we can put up models from ablation studies as well. For now, loading the dataset (SDD/UTH+ECY — which are be publicly available) directly and training without the social pooling layers should give results on this.

Regarding the truncation trick (TT), sampling from a truncated normal instead of N(0,1) will do the trick — although as shown in the paper this is helpful for few shot predictions and our provided code is for the standard K=20 where N(0,1) gives the best results. Happy to help with any followup questions.

**Comment by ksachdeva** [comment]
Thanks @karttikeya for this quick response. Much appreciated.

A few questions -

a) I managed to run your `test_pretrained_model.py` with PECNET_social_model1.pt and it shows ADE/FDE of 9.96/15.88 which did not match any row in Table 2 and then I looked at Table 1 which is for SDD and I find these numbers in that table.

I think there is a typo in your README where it says that we can reproduce results in Table 2. Maybe you meant Table 1. Please check/verify.

b) What is the difference between the 3 models that are archived in your repository?

c) I have not paid much attention yet to your formulation of social pooling and would prefer to first try your experiment without it (baby steps :) ) and on ETH. When you say train without social pooling layers is it as simple as commenting the loop that invokes `non_local_social_pooling`?  This line to be precise 
https://github.com/HarshayuGirase/PECNet/blob/9b649a942229b60d94c8bef766365c5745ac0091/utils/models.py#L155

Thanks for the guidance.

Regards
Kapil

**Comment by karttikeya** [comment]
Of course,
 
- Indeed, it looks like a small typo — our main dataset of interest was SDD so provided models are pre-trained on this dataset.
- All 3 models are trained on SDD — I believe there may be a few changes in hyperparameters (# of pooling layers etc.), but all 3 models are our social models for SDD.

- The pickle files we have provided in the repo are social pickle files based on thresholds for the SDD dataset. If you want to run on ETH/UCY you’d just have to pass in that data into the data loader instead (either raw or using the social utils preprocessing to group neighbors etc.). Yes — just commenting the line out will ensure no pooling layers are used.

- Scaled initial pos is used to allow the network to learn relative positions between pedestrians while matching element magnitudes.

**Comment by karttikeya** [comment]
Hope this answers your questions. I'm closing this issue for now. Please feel free to open another issue for other questions, star the repo if you found it helpful and thanks for interest in our code.
