### ISSUE TITLE
Implementation clarification appreciated 

### ISSUE THREAD

**Issue by xieshuaix** [HarshayuGirase/PECNet#10]
Thanks for sharing your code. Could you please explain the rationale behind the following implementations? Thanks.
1. Why is initial_pos down scaled by 1000? Also the number 7 below probably should be replaced by param in yaml, otherwise it can easily leads to ground truth leakage i.e. when we adjust observation horizon to 6.
https://github.com/HarshayuGirase/PECNet/blob/4c342597ca4310ef4976412dd8c829ad60a5465a/utils/social_utils.py#L155
2. At test time, your model first selects best destination estimation by comparing to ground truth destination, then predict trajectory conditioned on the best guess. Since your model already have access to ground truth at test time, why not just conditioning on the ground truth destination instead?
https://github.com/HarshayuGirase/PECNet/blob/4c342597ca4310ef4976412dd8c829ad60a5465a/scripts/test_pretrained_model.py#L66

**Comment by HarshayuGirase** [comment]
Hi,

1. Right -- we'll update this! Scaled initial pos is used to allow the network to learn relative positions between pedestrians while matching element magnitudes.

2. We use the ground truth to select the min error trajectory (we choose the best destination to be the best trajectory) of the K=20 predicted trajectories. See section 3.5 of this paper: [https://arxiv.org/pdf/1803.10892.pdf].

**Comment by karttikeya** [comment]
Hope this answers your questions. I'm closing this issue for now. Please feel free to open another issue for other questions, star the repo if you found it helpful and thanks for interest in our code.
