### ISSUE TITLE
Pretrained Models for ETH-UCY

### ISSUE THREAD

**Issue by os1a** [HarshayuGirase/PECNet#12]
Hi,
Thanks for the nice work, I have a question regarding reproducing the numbers in Table 2 (ETH-UCY).

Do you have the pretrained models, and also the testing script?

Thanks in advance,

**Comment by HarshayuGirase** [comment]
Hey @os1a ,

Thanks for your interest in our work/code -- hope it is helpful! We actually had not included pre-trained models/testing for the ETH-UCY datasets, as our main focus was SDD. However, the training/testing should be as simple as loading the ETH-UCY datasets and changing a couple hyperparameters. 

I believe @ksachdeva was able to reproduce the numbers on ETH-UCY and kindly has provided the notebook used for training/testing: https://github.com/HarshayuGirase/PECNet/issues/7#issuecomment-705223578

Hopefully this helps!

**Comment by karttikeya** [comment]
Hope this answers your questions. I'm closing this issue for now. Please feel free to open another issue for other questions, star the repo if you found it helpful and thanks for interest in our code.
