### ISSUE TITLE
Questions about ETH and UCY data processing

### ISSUE THREAD

**Issue by WW-Tong** [HarshayuGirase/PECNet#15]
Hi,
Thank you for your excellent work, I have a question about conducting experiments on ETH/UCY data.
I would like to know whether your data processing methods for ETH and UCY and the required data format are consistent with those in SGAN.
Thanks in advance,

**Comment by HarshayuGirase** [comment]
Hi,

Yes, we use the same ETH/UCY data that SGAN uses. We just create batches ourselves based on neighboring agents using the social masking script.

**Comment by os1a** [comment]
Hi,

Can you share the processed eth-ucy pickle files that you used for your paper? 
The original ones from SGAN has no masks and therefore we cannot apply your social pooling there.

Best,

**Comment by HarshayuGirase** [comment]
Hi,

We no longer have access to the server which had original processed pickle files and saved models for ETH/UCY, but I am working on getting these. I will let you know once I have updates!

**Comment by HarshayuGirase** [comment]
Hi,

The pickle files are available here: [https://drive.google.com/drive/folders/1ee9h_WtoXZhXZPT0H55uDFZaSmoArbf0?usp=sharing]

**Comment by FengHY-Chen** [comment]
Hi there, and thank you for your great work on PECNet!

I’m trying to apply PECNet to my own dataset, which is similar to ETH/UCY and contains four columns: timestamp, ID, X, Y. However, I couldn’t find the scripts for processing the raw ETH/UCY data. The link previously provided (https://drive.google.com/drive/folders/1ee9h_WtoXZhXZPT0H55uDFZaSmoArbf0?usp=sharing) seems to be broken.

Could you please share the data processing scripts or provide an updated link? Any guidance on the expected input format or preprocessing steps would also be greatly appreciated. Thank you so much for your help!
