### ISSUE TITLE
input data for the model

### ISSUE THREAD

**Issue by audengxiao** [HarshayuGirase/PECNet#16]
hi, I hava a question about input data, in function collect_data, input is [person_id, frame_id ,x, y], here what's "x, y" refering to?
and while in your pickled data, input data is bounding box coordinates [xmin, ymin, xmax, ymax]

**Comment by HarshayuGirase** [comment]
Hi,

The "x" and "y" refer to the agents' (x,y) coordinates in pixel space.

**Comment by karttikeya** [comment]
Hope this answers your questions. I'm closing this issue for now. Please feel free to open another issue for other questions, star the repo if you found it helpful and thanks for interest in our code.
