### ISSUE TITLE
Problem in the prediction result

### ISSUE THREAD

**Issue by Kguo-cs** [HarshayuGirase/PECNet#17]
In the prediction process, you use all the pedestrains in the scene to predict their future. Therefore, you may use the same or neighbor pedestrain's future trajectories for the prediction. I think it will invalidate your result. Is it correct?

**Comment by Kguo-cs** [comment]
Besides, the mask use groud truth information.

**Comment by HarshayuGirase** [comment]
Hi,

The masks are made to pool neighboring agents together. The masks do use ground-truth observation data (from the past trajectory history) but do not use any future information that can result in ground-truth leakage.

**Comment by karttikeya** [comment]
Hope this answers your questions. I'm closing this issue for now. Please feel free to open another issue for other questions, star the repo if you found it helpful and thanks for interest in our code.
