### ISSUE TITLE
Is initial_pos required if not doing social pooling ?

### ISSUE THREAD

**Issue by ksachdeva** [HarshayuGirase/PECNet#2]
Hi @karttikeya 

This is a follow-up question based on your answer in the previous queries

Your answer:

> Scaled initial pos is used to allow the network to learn relative positions between pedestrians while matching element magnitudes.

Based on this I am assuming that if not doing social pooling then it is okay to not take initial_pos into account. Is that correct understanding?

Regards & thanks
Kapil

**Comment by karttikeya** [comment]
Yes, I believe that's correct.

**Comment by karttikeya** [comment]
Hope this answers your questions. I'm closing this issue for now. Please feel free to open another issue for other questions, star the repo if you found it helpful and thanks for interest in our code.
