### ISSUE TITLE
Homographic Matrix for UCY used in Y-Net

### ISSUE THREAD

**Issue by HRHLALALA** [HarshayuGirase/PECNet#27]
Hi, I am building the dataset for UCY and ETH dataset. To conduct a fair experiment, can you provide the homographic matrix used for UCY? Also, do you use same scene images among uni_examples and UNIV (student00*) as well as among Zara * datasets?  Thanks.

**Comment by sff1019** [comment]
@HRHLALALA Hi, I was wondering if you got similar results as the paper for Y-Net on ETH and UCY dataset. Thanks.

**Comment by HRHLALALA** [comment]
> @HRHLALALA Hi, I was wondering if you got similar results as the paper for Y-Net on ETH and UCY dataset. Thanks.

I am currently using the dataset from Social GAN to train but unfortunately not yet got the results. I will let you know when the results come out.

**Comment by sff1019** [comment]
Thanks for the quick response! 
I see, FYI I've trained a new model using the dataset from Social GAN and for the ETH split I've got 
```
ADE: 0.58 (paper: 0.28)
FDE: 0.84 (paper: 0.33)
```
This is unfortunately very different from the original numbers in the paper.  It would be great if you can check it with yours once you have it.
Thanks.

**Comment by Kay1794** [comment]
> Thanks for the quick response! I see, FYI I've trained a new model using the dataset from Social GAN and for the ETH split I've got
> 
> ```
> ADE: 0.58 (paper: 0.28)
> FDE: 0.84 (paper: 0.33)
> ```
> 
> This is unfortunately very different from the original numbers in the paper. It would be great if you can check it with yours once you have it. Thanks.

Hi @sff1019, I know it may be a little bit outdated, but I am wondering if you have achieved similar numbers on the Social GAN split for the ETH dataset? Any comments would be highly appreciated!

**Comment by SunshineDHW** [comment]
> Thanks for the quick response! I see, FYI I've trained a new model using the dataset from Social GAN and for the ETH split I've got
> 
> ```
> ADE: 0.58 (paper: 0.28)
> FDE: 0.84 (paper: 0.33)
> ```
> 
> This is unfortunately very different from the original numbers in the paper. It would be great if you can check it with yours once you have it. Thanks.

Hi:
  @sff1019,Could you tell me How to implement YNet?What changes have you made based on SDD? Thank you for you help1

**Comment by rashidch** [comment]
Hi Everyone,

As the link to homography matrices is broken. Please can anyone share the homography matrices again?

> Hi, thanks for your interest in our work. Here are the homography matrices:
> 
> https://drive.google.com/drive/folders/1ycxLUluANUXSHNmJQ8w4Nx8nVQXiB2F3.
> 
> For univ, we use the same scene images but for zara1,2 there is a very slight difference between the reference images.
