### ISSUE TITLE
Hi, Can you provide the segmentation_models of eth_ucy?

### ISSUE THREAD

**Issue by LXY572** [HarshayuGirase/PECNet#37]

**Comment by HarshayuGirase** [comment]
Hi, 

For ETH/UCY we used the semantic maps provided in the drive link

**Comment by JiyouSeo** [comment]
Hello @HarshayuGirase, 
Is the link expired now?
I cannot click the link that you wrote.

**Comment by JiyouSeo** [comment]
@HarshayuGirase 
Hello, I want you to provide it too!
Thank you

**Comment by JiyouSeo** [comment]
Hello, can I let me know where is ETH/UCY semantic maps? 
I downloaded ynet_additional_files, and there are SDD, inD semantic_maps directories as {data_name}_mask.png format ,
However, there are only oracle.png in ETH/UCY directories..

Thank you
