### ISSUE TITLE
YNet ETH Dataset Moving Camera

### ISSUE THREAD

**Issue by AndreHenkel** [HarshayuGirase/PECNet#38]
Hello,

In your paper YNet you talked about using ETH/UCY and I was wondering if you also tested your network on the moving ego perspective of ETH. (Mounted camera rig on the car)
If so, I wanted to ask if you normalized the pedestrian coordinates to a certain frame, and which frame from the video-sequence you used as input to your YNet model. I.e. the initial image of the video-sequence or the last image of the observation.

Thank you very much in advance.

André Henkel

**Comment by ArcaneEmergence** [comment]
Hi André,

We have only used bird-view perspective trajectories without moving the camera, as used in Social GAN and the other benchmarked methods.

It would be interesting to see how Y-net can be modified into an ego and moving perspective. From my gut feeling, the (static) ego-view alone wouldn't pose a big challenge if you retrain the model on enough data. For the moving camera part, I believe deeper changes in the model may be necessary. Or without changing the model, you would need to have a SLAM preprocessing step to create a map of the environment beforehand, project the pedestrian positions onto the map's coordinate system and use those as input into Y-net.

Wish you lots of success!

Best,
Yang

**Comment by AndreHenkel** [comment]
Thank you! :)
