### ISSUE TITLE
Question about the preprocessed data for ETH/UCY

### ISSUE THREAD

**Issue by letme-hj** [HarshayuGirase/PECNet#39]
Hi, 
thank you very much for your nice work and sharing it!

I have a question regarding the preprocessed data you provided (through Google Drive).
Among the datasets provided, I found out that some of the samples in pickle file for eth/ucy dataset are the same, but with different metaIds.
For example in hotel_train.pkl, it has samples of different metaId with everything else the same (trackId=1.0, sceneId='students001', and same frameIds as well as their x, y coordinates). Other files also contain some same samples like this.
I believe I did not modify the pickle file, but please let me know if this is not the case!

If it is, is this what was intended or should I remove the duplicated ones for further trials?

Sorry, in advance, to bother you if I misunderstood the purpose of metaId and this is totally fine!

**Comment by ArcaneEmergence** [comment]
Hi, yes this is correct, metaId is simply a unique ID for each sample within a dataset (say only within hotel_train.pkl, eth_train.pkl, ...), but not across datasets. 

And regarding the files, *_train.pkl is the whole dataset without the * dataset (e.g. * = "eth"), so you can report scores on the unseen * dataset (contained in *_test.pkl). So you would only use one pair of *_train.pkl and *_test.pkl at a time. Don't mix different *_train.pkl, as this would include duplicates and data leakage for the *_test.pkl.
