### ISSUE TITLE
time cost

### ISSUE THREAD

**Issue by ynw2021** [HarshayuGirase/PECNet#40]
Hello, thanks for sharing your code!
I am wondering how much time does it cost for you to train your y-net model? And how many gpus do you use? I use one titian xp and it seems to cost me 2 days for training. Is that normal?

**Comment by ArcaneEmergence** [comment]
On one single old RTX 2080 gpu, training to the best SOTA result can take upto a couple of days. But it can be made significantly faster by 

1. Simply skipping intermediate evaluations (which are time expensive and do not improve model performance)
2. Setting a smaller K_e and K_a for evaluations.
3. .. or simply modern GPUs.
