### ISSUE TITLE
[Solved] Reproduced ETH Result

### ISSUE THREAD

**Issue by SaoDiSengA** [HarshayuGirase/PECNet#53]
Hi @karttikeya 

This is to confirm that indeed 170 does benefit.

Here is a new notebook in which I am training ETH

https://colab.research.google.com/drive/1OdVwL3CM-_f-T3HlHyY3B2IaTDiKmprs?usp=sharing

This notebook has some differences from code in your repository because of the data preparation part. Everything is in the notebook itself including downloading of datasets etc.

Above to reproduce similar results as paper. Some of the runs produced even a better number.

Would appreciate if you have a cursory look to see I am not doing anything wrong as even though I managed to reproduce your numbers with machine learning it is easy to get fooled.

##

Again I want to thank you for the time you spent answering the questions; I am very happy that the results of your paper can be reproduced. This is an achievement in itself and indeed a good job on your part and your co-authors.

Regards
Kapil

_Originally posted by @ksachdeva in https://github.com/HarshayuGirase/Human-Path-Prediction/issues/7#issuecomment-705223578_

**Comment by karttikeya** [comment]
Hi @SaoDiSengA , 

Thanks for your message and confirming the reproduction and sharing the notebook. 

Here is my copy of the same notebook (for redundancy): [ETH result](https://colab.research.google.com/drive/1DYf94zHCniVDSIx57M21uwVx3HFBXfDZ?usp=sharing)

 
This would help future users to be able to follow a 3rd party reproduction.

**Comment by SaoDiSengA** [comment]
> Hi @SaoDiSengA ,
> 
> Thanks for your message and confirming the reproduction and sharing the notebook.
> 
> Here is my copy of the same notebook (for redundancy): [ETH result](https://colab.research.google.com/drive/1DYf94zHCniVDSIx57M21uwVx3HFBXfDZ?usp=sharing)
> 
> This would help future users to be able to follow a 3rd party reproduction.

but,i want to get other npz files,like ucy,sdd

**Comment by haofuly** [comment]
Hi @SaoDiSengA 
Glad to see your reproduction on ETH.
It seems that the link of your ETH config has expired. Could you share again or tell me what modification have you made compared to the original config except the 170 batchsize?
Thanks for helping
