### ISSUE TITLE
Question - Prior - Training vs Testing

### ISSUE THREAD

**Issue by ksachdeva** [HarshayuGirase/PECNet#6]
Hi @karttikeya 

I noticed that during the training that a standard normal prior is assumed to compute the KL Loss. However, in the testing/evaluation, I see this hyperparameter for sigma (value set to 1.3) https://github.com/HarshayuGirase/PECNet/blob/4c342597ca4310ef4976412dd8c829ad60a5465a/utils/models.py#L127

Two questions -

a) Why this difference? i.e why not use 1.3 during training as well to compute the KL ?
b) How did you find 1.3?

Regards & thanks
Kapil

**Comment by karttikeya** [comment]
Please see Section 3.1 of the [paper](https://arxiv.org/pdf/2004.02025.pdf). 

> In contrast, in situations where a high number of predictions are to be generated (such as K = 20, a standard
> setting on benchmarks) we propose to use σT > 1 with no truncation. We posit that this procedure allows simple adjustment of prediction diversity in favor of overall performance for different K, thereby providing a simple method of
> achieving good performance in all settings without requiring any retraining.

**Comment by ksachdeva** [comment]
Thanks. Missed this part.
