### ISSUE TITLE
Question - data scaling (applicable for ETH ?)

### ISSUE THREAD

**Issue by ksachdeva** [HarshayuGirase/PECNet#7]
Hi @karttikeya 

I understand the notion of shifting the dataset to have the same origin. You also multiply the trajectories by 1.86.

- Is this number has any significance?
- Is it the same hyper-parameter used for ETH as well?

Regards
Kapil

**Comment by karttikeya** [comment]
We noticed scaling the data helped slightly with better optimization (note, same effect might be possible by tuning lambda1 & lambda2 instead). To keep other hyperparameters the same, we scaled the ETH trajectories to be on the order of magnitude of SDD trajectories ( about 170 I believe).

**Comment by ksachdeva** [comment]
Ah. I tried to train ETH this morning but no success. Will try this suggestion now to scale the trajectories first.

**Comment by ksachdeva** [comment]
Hi @karttikeya 

This is to confirm that indeed 170 does benefit.

Here is a new notebook in which I am training ETH

https://colab.research.google.com/drive/1OdVwL3CM-_f-T3HlHyY3B2IaTDiKmprs?usp=sharing

This notebook has some differences from code in your repository because of the data preparation part. Everything is in the notebook itself including downloading of datasets etc.

Above to reproduce similar results as paper. Some of the runs produced even a better number.

Would appreciate if you have a cursory look to see I am not doing anything wrong as even though I managed to reproduce your numbers with machine learning it is easy to get fooled.

##

Again I want to thank you for the time you spent answering the questions; I am very happy that the results of your paper can be reproduced. This is an achievement in itself and indeed a good job on your part and your co-authors.

Regards
Kapil

**Comment by HarshayuGirase** [comment]
Hi @ksachdeva, 

That's nice that you were able to reproduce it! I took a glance and it looked good to me -- perhaps this might be useful to add to our repo for others training on UTH/ECY. If you'd like to add a PR with this notebook, we'd be happy to include it.

**Comment by ksachdeva** [comment]
Thanks @HarshayuGirase, I will send the PR tonight.

**Comment by karttikeya** [comment]
Thank you for your contribution. I'm closing this issue for now. Please feel free to open another issue for other questions, star the repo if you found it helpful and thanks for interest in our code.

**Comment by Khrylx** [comment]
@ksachdeva, thanks for providing the notebook! However, based on the notebook's log and my own run, the performance for ADE/FDE is around 0.58/0.84, which is far from that in the paper (0.29/0.48). Would you mind sharing your config YAML file for reproducing the results? 
Thanks in advance!

**Comment by sjtuxcx** [comment]
@ksachdeva Hi, May I ask how you generate the eth npz file? I use my eth data but receive a poor performance and I notice there are 30000+ trajectories in your dataset but only 3000+ trajectories in my eth data. Could you share the data generation code?

**Comment by SaoDiSengA** [comment]
> 

hi,can you provide the other npz file?Or the processing script!Thanks a lot!

**Comment by SaoDiSengA** [comment]
> @ksachdeva Hi, May I ask how you generate the eth npz file? I use my eth data but receive a poor performance and I notice there are 30000+ trajectories in your dataset but only 3000+ trajectories in my eth data. Could you share the data generation code?

hi,i got the same question,do you solve the problem?

**Comment by SaoDiSengA** [comment]
@ksachdeva Could you share the data generation code?i want to generate the npz file,but i can't solve this.
