### ISSUE TITLE
Able to get good/comparable results for SDD in Ours-S-TT configuration

### ISSUE THREAD

**Issue by ksachdeva** [HarshayuGirase/PECNet#8]
Hi @karttikeya 

You will find this interesting 

Here is a colab notebook that has code from this repository with a change that I removed the code related to anything social and initial_pos.

https://colab.research.google.com/drive/1p2NsydskxlJpN9FQjsIuBYt023SK03P9?usp=sharing

You will see that during training it showing best as 

Test Min FDE 16.265123988001477
Test Best ADE Loss So Far (N = 20) 10.08790206860359
Test Best Min FDE (N = 20) 15.723517020260925

and in the independent testing of the model it is showing

Average ADE: 10.166523163287923
Average FDE: 16.0149660701936

(I was earlier confused and did not pay attention to "average" ... numbers during the training looked better because during test you are taking an average over 150 runs so it makes sense)

Regards
Kapil

**Comment by HarshayuGirase** [comment]
Hi,

That is correct -- it's averaged during test so the signal on the test/val set during training may be slightly noisy. Correct me if I'm wrong, but it seems as though you are using the TT (sampling with >1 SD at test time which is the default we had set for K=20)?

**Comment by ksachdeva** [comment]
HI @HarshayuGirase 

Apologies for the late reply.

I did not change the number of samples to 1. It is still K=20.  The scale used is 1.3 (as in your original implementation)

Regards
Kapil

**Comment by HarshayuGirase** [comment]
Hi @ksachdeva,

Thanks for clarifying. It seems as though you are using the TT, as the SD is 1.3 (different than what was used in training). Please see the **Truncation Trick** in section 3.1. For larger sample sizes (K=20), instead of truncating, we use a larger SD for better sample diversity, so this model you experimented with would just be O-S. Setting the SD to 1 during test time would correspond to the O-S-TT ablation.

**Comment by ksachdeva** [comment]
Thanks @HarshayuGirase  

It makes sense now. I would try again with SD = 1 during test.

> as the SD is 1.3 (different than what was used in training).

I got 1.3 from your configuration file. I am assuming it is valid for SDD, was it different for ETH ?

Regards
Kapil

**Comment by HarshayuGirase** [comment]
No problem @ksachdeva !

Yes, our default parameters in config file were the best parameters we found for K=20 (so it includes social + changing SD trick). I believe it was the same for ETH/UCY. I'll close this issue for now -- feel free to open another issue for other questions!
