### ISSUE TITLE
How does the social mask get created?

### ISSUE THREAD

**Issue by Yijun88** [HarshayuGirase/PECNet#9]
Hi @karttikeya ,

First of all, very nice work for PECNet! The idea of path planning conditioned on endpoints is really interesting. I have two questions regarding the training procedures:
1) how does the social mask corresponds to the social IDs?
I understand intuitively the social masks are used to indicate whether in spatial and temporal domain two objects interacts with each other. And due to the limit of GPU power, you are manually creating each batch and their social masks. But why you are using current_size to represent the index within a mask given they are always incrementing by 1? Maybe some explanation of the current_size and the object could help.
https://github.com/HarshayuGirase/PECNet/blob/4c342597ca4310ef4976412dd8c829ad60a5465a/utils/social_utils.py#L121-L128

2) why initial poses are downscaled by 1000 while the past trajectories are upscaled by 1.86? 
Are those just magic numbers or there's a rationale on how to select those?

Best,
Yijun

**Comment by HarshayuGirase** [comment]
Hi,

1. Current size keeps track of how many pedestrians have been added to this batch so far. Currently in code, the social mask will be a series of block 1 matrices (check paper for details). Thus, a naive solution was just to keep a track of current index and neighbors — for example if indices [22,23,24] of the batch are neighbors (always contiguous by setup) then you will see in mark_similar, [i,j] will be 1 for all combinations of the above “related_list”. Hope this helps.

2. Yes, it was scaled to match magnitudes of features and tuned while training. Please see [https://github.com/HarshayuGirase/PECNet/issues/7#issuecomment-705142309]

**Comment by karttikeya** [comment]
Hope this answers your questions. I'm closing this issue for now. Please feel free to open another issue for other questions, star the repo if you found it helpful and thanks for interest in our code.
